// Game metadata only — no component imports, so game files can import this
// without creating a circular dependency with index.js.
export const GAME_LIST = [
  {
    id: 'age-invaders',
    title: 'AGE INVADERS',
    emoji: '👾',
    color: '#a45bff',
    tagline: 'The signs of aging descend relentlessly — fight back!',
    howTo: 'Fine lines 〰️, wrinkles ➿, sun spots 🟤, and sagging 🫠 march down in waves — ← → to move (or drag), SPACE / tap to fire your treatment. Catch falling peptides (🧪 NAD+, ✨ GLOW, 🫧 GLUTATHIONE for the sun spots...) but DODGE the agers ☀️🍩😰📱. Shoot ⏳ Father Time for +150. Every wave is a new decade!',
  },
  {
    id: 'plaque-breaker',
    title: 'PLAQUE BREAKER',
    emoji: '🧱',
    color: '#22e5ff',
    tagline: 'Smash the plaque — clear skin, clear board!',
    howTo: 'Drag (or ← →) to move the paddle and bounce the ball into the plaque wall. ✨ bricks drop peptide power-ups: 🛡️ GHK-CU wide paddle, ✨ GLOW multi-ball, 🧘 MAGNESIUM slow-mo. Clear the board to level up — 3 lives!',
  },
  {
    id: 'vial-stacker',
    title: 'VIAL STACKER',
    emoji: '🏗️',
    color: '#ffe94a',
    tagline: 'Stack the vial trays sky-high — don\'t slip!',
    howTo: 'One button: SPACE / tap to drop the sliding tray onto the stack. Any overhang gets sliced off, so the tower keeps narrowing — land it PERFECT to keep your width and bank streak bonuses. Miss the stack and it\'s over!',
  },
  {
    id: 'clinic-crossing',
    title: 'CLINIC CROSSING',
    emoji: '🚶',
    color: '#ff2fb9',
    tagline: 'Get your patient to the medspa — mind the hazards!',
    howTo: 'Hop with arrows/WASD (or the pad) across the hazard lanes — dodge 📄 paperwork, 🛵 couriers, 🍩 sugar, ☀️ UV rays, and 📱 doomscrollers. Reach the 🏥 door for +100, then the shift speeds up. 3 lives!',
  },
  {
    id: 'dna',
    title: 'CLEAN DNA',
    emoji: '🧬',
    color: '#4dff5e',
    tagline: 'Grow the strand, gobble the pills!',
    howTo: 'Steer the DNA strand with arrows/WASD (or the pad). Eat pills 💊 to grow and speed up, grab the flashing 💉 for +30 before it fades. Hit a wall or yourself and the strand unravels!',
  },
  {
    id: 'glow-up',
    title: 'GLOW UP',
    emoji: '✨',
    color: '#ffe94a',
    tagline: 'Bounce up the wellness ladder to peak glow!',
    howTo: 'Bounce ever upward! ← → to steer (or drag on mobile) — land on pill platforms, grab ✨💊 for bonus points, and hit 💆 spa springs for MEGA bounces. Orange platforms crack. Fall and it\'s over!',
  },
  {
    id: 'peptide-panic',
    title: 'PEPTIDE PANIC',
    emoji: '😮',
    color: '#ff2fb9',
    tagline: 'Catch the good vials, dodge the sketchy stuff!',
    howTo: 'Move the hungry mouth 😮 with ← → arrows (or drag on mobile). Gobble vials 💉🧪💊 for points and build combos — but swallow a counterfeit ☠️ or the DEA barrel 🛢️ and lose a life. 3 lives!',
  },
  {
    id: 'gains-run',
    title: 'GAINS RUN',
    emoji: '🏃',
    color: '#22e5ff',
    tagline: 'One-button flight down the clinic hallway!',
    howTo: 'Tap SPACE / click to flap down the clinic hallway. Grab pickups 💊🥗💉🧬 for bonus points and dodge the walls. One crash and it\'s over!',
  },
  {
    id: 'script-sorter',
    title: 'SCRIPT SORTER',
    emoji: '📋',
    color: '#4dff5e',
    tagline: 'Sort the scripts before the conveyor jams!',
    howTo: 'A script slides in — press 1 (PEPTIDE), 2 (TRT), 3 (HRT), or 4 (REJECT), or tap the bins. Sort right for points; 3 mis-sorts and the pharmacy shuts down. It speeds up!',
  },
  {
    id: 'perfect-dose',
    title: 'PERFECT DOSE',
    emoji: '🎯',
    color: '#ffe94a',
    tagline: 'Stop the needle in the therapeutic window!',
    howTo: 'The needle sweeps across ONCE — press SPACE / tap to stop it inside the green therapeutic window before it reaches the end. Dead center = PERFECT. The window shrinks every round. 3 misses and you\'re done!',
  },
  {
    id: 'symptom-smack',
    title: 'SYMPTOM SMACK',
    emoji: '🖐️',
    color: '#ff8a3d',
    tagline: 'Whack the symptoms as they pop up!',
    howTo: 'Symptoms pop out of the holes — smack them with a click/tap before they hide! Don\'t smack the happy patients 😊. 45 seconds on the clock!',
  },
  {
    id: 'peptide-or-pretend',
    title: 'PEPTIDE OR PRETEND?',
    emoji: '🧠',
    color: '#a45bff',
    tagline: 'Real compound... or total nonsense?',
    howTo: 'We show you a name — you call it: REAL peptide/compound or PRETEND made-up nonsense. Answer fast for bonus points. 3 strikes and the quiz master wins!',
  },
  {
    id: 'vial-pairs',
    title: 'VIAL PAIRS',
    emoji: '🃏',
    color: '#22e5ff',
    tagline: 'Flip and match the product vials!',
    howTo: 'Flip two cards at a time to find matching vials. Fewer flips and faster time = bigger score. Clear the whole fridge!',
  },
  {
    id: 'merge-lab',
    title: 'MERGE LAB',
    emoji: '⚗️',
    color: '#4dff5e',
    tagline: 'Merge vials into legendary formulas!',
    howTo: 'Tap FILL to make basic vials, then tap a vial and tap its matching twin to merge them into something stronger. Reach the mythic ✨ GOLDEN FORMULA before the 90-second shift ends!',
  },
]

export const GAME_META = Object.fromEntries(GAME_LIST.map((g) => [g.id, g]))
